# Generated by Django 3.0.7 on 2020-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My CA2020 blog!', max_length=300),
        ),
    ]
